Ft/td 138/gh action
valitydev/hooker pull request #1
Opened 2022-02-18 14:10 UTC by inallyoung

2022-03-11 11:16 UTC, strug requested changes
Основной момент на который хочется обратить внимание, что для данного подхода нужна четкая цепочка событий тоесть родитель - родитель - событие и не должно быть зависимостей косвенных типо событие по инвойсу зависит от события по кастомеру (пишу просто чтоб подсветить). Если этого нет, то было бы круто если бы ты приложил сюда последовательность статусов и событий как по ним будут уходить хуки (что-то типо графа)

2022-03-11 11:16 UTC, strug commented on src/main/java/dev/vality/hooker/listener/CustomerMachineEventHandler.java
>              log.error("Error when poller handling with id {}", id, e);
если углубиться в метода выше customerMessageService.process(message); то будет видно при ошибке отправки в кафку этот try - catch позволит потерять сообщение

2022-03-11 11:16 UTC, strug commented on src/main/java/dev/vality/hooker/handler/customer/AbstractCustomerEventMapper.java
> +    }
как будто названия разъехались исторически Mapper и метод handle

2022-03-11 11:16 UTC, strug commented on src/main/java/dev/vality/hooker/handler/customer/AbstractCustomerEventMapper.java
> +    protected abstract CustomerMessage buildEvent(CustomerChange cc, EventInfo eventInfo) throws DaoException;
пытался понять сакральный смысл этого метода (не смог), вроде как можно без неого обойтись и мб весь этот абстрактный класс тоже не нужен?

2022-03-11 11:16 UTC, strug commented on src/main/java/dev/vality/hooker/handler/Mapper.java
>  public interface Mapper<C, M extends Message> {
вот это наверно реально Handler ниже поднимается эта тема, вроде как методы больше Handler подходят про маппинг ничего то и нет

2022-03-11 11:16 UTC, strug commented on src/main/java/dev/vality/hooker/utils/PaymentToolUtils.java
> +                            paymentTool.getBankCard().getTokenProviderDeprecated().name()) : null)
: null тоже бы на новую строку

2022-03-11 13:03 UTC, inallyoung commented on src/main/java/dev/vality/hooker/dao/impl/InvoicingDaoImpl.java
> +                " order by id desc limit 1 ";
все ок, модифицировал тест под этот кейс, корректно возвращает родительский id

2022-03-11 13:05 UTC, inallyoung commented on src/main/java/dev/vality/hooker/service/MessageService.java
> +    public void process(T message) {
там основная обработка происходит (маппинг, сэйв и отправка в кафку). Хз как назвать.

2022-03-11 13:39 UTC, inallyoung commented on src/main/java/dev/vality/hooker/listener/CustomerMachineEventHandler.java
>              log.error("Error when poller handling with id {}", id, e);
пофиксил

2022-03-11 13:58 UTC, inallyoung commented
@strug 
Зависимостей между событиями нет, инвойсы не зависят от кастомеров.
что касается графа  - есть ли в нем необходимость? Хуки должны уходить в порядке их получения из кафки. Последовательность изменения статусов прежняя, то есть InvoiceCreated -> PaymentPending -> PaymentProcessed -> PaymentCaptured -> InvoicePaid
Родительским для каждого события считается предыдущее событие, кроме InvoiceCreated (для него -1).

2022-03-14 10:17 UTC, strug commented
> @strug Зависимостей между событиями нет, инвойсы не зависят от кастомеров. что касается графа - есть ли в нем необходимость? Хуки должны уходить в порядке их получения из кафки. Последовательность изменения статусов прежняя, то есть InvoiceCreated -> PaymentPending -> PaymentProcessed -> PaymentCaptured -> InvoicePaid Родительским для каждого события считается предыдущее событие, при условии, что для его типа есть хук, кроме InvoiceCreated (для него -1).

да звучит норм, этого достаточно) просто хотел убедиться

2022-03-14 10:20 UTC, strug commented on src/main/java/dev/vality/hooker/listener/CustomerMachineEventHandler.java
> +            EventPayload payload = parser.parse(me);
такие жирные лямбды лучше в метод, а то там внутри еще лямбды

2022-03-14 10:20 UTC, strug commented on src/main/java/dev/vality/hooker/listener/InvoicingMachineEventHandler.java
> +                                }
короче я бы все что в лябдах в {} заворачивал в методы, а то не читабельно

2022-03-15 08:23 UTC, strug approved these changes

2022-03-15 08:27 UTC, merged